### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by banduoba** [kajweb/douyin_downloader#1]
目前解析了链接下载的视频提示视频已丢失

**Comment by kajweb** [comment]
估计这个方法凉了

**Comment by banduoba** [comment]
还维护么你这个

**Comment by kajweb** [comment]
找到新渠道再维护，看市面上的解析器应该还有其他解析方法的。

**Comment by steven7851** [comment]
请求要加上`user-agent` 只能是 Android 或 iOS 的
Ex:`headers = {'user-agent': 'Mozilla/5.0 (Linux; U; Android 5.1.1; zh-cn; MI 4S Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.146 Mobile Safari/537.36 XiaoMi/MiuiBrowser/9.1.3'}`

**Comment by kajweb** [comment]
@banduoba 已更新
