### ISSUE TITLE
把playwm 换成 play失效

### ISSUE THREAD

**Issue by j5465** [kajweb/douyin_downloader#3]
昨天还可以，今天就不行了

**Comment by kajweb** [comment]
你好，请问您使用python版本还是electron还是electron编译版？
还有报错有提示吗？

**Comment by j5465** [comment]
python 版，
没有错误提示，因为用换成play的url，下载出来的0字节
把url放在浏览器里什么也没有，
正常的应该是放到浏览器里就提示下载一个mp4文件的嘛
后来自己了，在config.ini改了一下android-headers

**Comment by kajweb** [comment]
正常是自动下载到download目录的……您可以先确认一下链接是否正常……
目前使用的是`Mozilla/5.0 (Linux; U; Android 5.1.1; zh-cn; MI 4S Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.146 Mobile Safari/537.36 XiaoMi/MiuiBrowser/9.1.3`应该没问题。

**Comment by j5465** [comment]
之前下载挺多次了，下载到download目录正常，playwm 那个url也正常，打开就开始下载了，
但是换成play打开url就是一个空白页面，所以那个id.mp4 是0字节
我就把zh-cn换成了en-us，就可以了。

**Comment by kajweb** [comment]
您好，链接直接在浏览器打开的话，如果是PC-UA的话是空白的，用chrome改为手机UA即可正常打开。
`download_douyin()`已经默认为移动端ua，理论上通过脚本下载的视频应该不是0byte。
